apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-archive-dispatch-gateway
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/instance: fint-flyt-archive-dispatch-gateway_fintlabs_no
    app.kubernetes.io/name: fint-flyt-archive-dispatch-gateway
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-flyt-archive-dispatch-gateway:sha-0000000
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
    - name: fint.client.base-url
      value: path
    - name: fint.dispatch-gateway.authorization.enable
      value: 'true'
  onePassword:
    itemPath: "vaults/aks-alpha-vault/items/fint-flyt-archive-fint-client-innlandetfylke-no"
  envFrom:
    - secretRef:
        name: fint-resource-gateway-op
    - secretRef:
        name: fint-flyt-file-oauth2-client
  resources:
    limits:
      memory: "2048Mi"
      cpu: "1"
    requests:
      memory: "512Mi"
      cpu: "100m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }