spring:
  security:
    oauth2:
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer=fint-api
        registration:
          fint:
            authorization-grant-type: password
            provider: fint-idp
            scope: fint-client
fint:
  flyt:
    file-service-url: 'http://fint-flyt-file-service:8080'