fint:
  flyt:
    gateway:
      application:
        archive:
          client:
            fint-archive:
              registration-id: fint
              username: ${fint.core.oauth2.username}
              password: ${fint.core.oauth2.password}
spring:
  security:
    oauth2:
      client:
        registration:
          fint:
            authorization-grant-type: password
            provider: fint-idp
            scope: fint-client
            client-id: ${fint.core.oauth2.client-id}
            client-secret: ${fint.core.oauth2.client-secret}