apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vlfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-archive-gateway_vlfk_no
      fintlabs.no/org-id: vlfk.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-archive-gateway_vlfk_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vlfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "vlfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/vlfk-no"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/beta/vlfk-no/actuator/prometheus"
      - op: replace
        path: "/spec/prometheus/path"
        value: "/beta/vlfk-no/actuator/prometheus"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/vlfk-no/api/intern/arkiv"
      - op: replace
        path: "/spec/env/3/value"
        value: "https://beta.felleskomponent.no"
      - op: replace
        path: "/spec/env/4/value"
        value: |
          {
            "vlfk.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
      - op: add
        path: "/spec/env/-"
        value:
          name: "logging.level.no.fintlabs"
          value: "DEBUG"
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-v1-slack-webhook"
    target:
      kind: Application
      name: fint-flyt-archive-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-archive-fint-client_vlfk_no"
      - op: replace
        path: "/spec/orgId"
        value: "vlfk.no"
    target:
      kind: FintClient
      name: fint-flyt-archive-fint-client

