apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vestfoldfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-archive-gateway_vestfoldfylke_no
      fintlabs.no/org-id: vestfoldfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-archive-gateway_vestfoldfylke_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vestfoldfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "vestfoldfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/vestfoldfylke-no"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/vestfoldfylke-no/actuator/prometheus"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/vestfoldfylke-no/api/intern/arkiv"
      - op: replace
        path: "/spec/env/3/value"
        value: "https://api.felleskomponent.no"
      - op: replace
        path: "/spec/env/4/value"
        value: |
          {
            "vestfoldfylke.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-api-vault/items/fint-flyt-v1-slack-webhook"
    target:
      kind: Application
      name: fint-flyt-archive-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-archive-fint-client_vestfoldfylke_no"
      - op: replace
        path: "/spec/orgId"
        value: "vestfoldfylke.no"
    target:
      kind: FintClient
      name: fint-flyt-archive-fint-client
