apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afk-no

resources:
  - ../../../base

commonLabels:
  fintlabs.no/org-id: afk.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-archive-gateway_afk_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "afk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/afk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/afk-no/api/intern/arkiv"
      - op: replace
        path: "/spec/env/3/value"
        value: "https://api.felleskomponent.no"
      - op: replace
        path: "/spec/env/4/value"
        value: |
          {
            "afk.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "frid-iks.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-api-vault/items/fint-flyt-v1-slack-webhook"
    target:
      kind: Application
      name: fint-flyt-archive-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-archive-fint-client_afk_no"
      - op: replace
        path: "/spec/orgId"
        value: "afk.no"
    target:
      kind: FintClient
      name: fint-flyt-archive-fint-client
