apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-archive-gateway_nfk_no
      fintlabs.no/org-id: nfk.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-archive-gateway_nfk_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "nfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "nfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/nfk-no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/nfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/nfk-no/api/intern/arkiv"
      - op: replace
        path: "/spec/env/3/value"
        value: "https://api.felleskomponent.no"
      - op: replace
        path: "/spec/env/4/value"
        value: |
          {
            "nfk.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
    target:
      kind: Application
      name: fint-flyt-archive-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-archive-fint-client_nfk_no"
      - op: replace
        path: "/spec/orgId"
        value: "nfk.no"
    target:
      kind: FintClient
      name: fint-flyt-archive-fint-client
