apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tromsfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-archive-gateway_tromsfylke_no
      fintlabs.no/org-id: tromsfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-archive-gateway_tromsfylke_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "tromsfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "tromsfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/tromsfylke-no"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/beta/tromsfylke-no/actuator/prometheus"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/tromsfylke-no/api/intern/arkiv"
      - op: replace
        path: "/spec/env/3/value"
        value: "https://beta.felleskomponent.no"
      - op: replace
        path: "/spec/env/4/value"
        value: |
          {
            "tromsfylke.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
    target:
      kind: Application
      name: fint-flyt-archive-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-archive-fint-client_tromsfylke_no"
      - op: replace
        path: "/spec/orgId"
        value: "tromsfylke.no"
    target:
      kind: FintClient
      name: fint-flyt-archive-fint-client
