apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-archive-gateway
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-flyt-archive-gateway
    app.kubernetes.io/instance: fint-flyt-archive-gateway_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-flyt-archive-gateway:sha-0000000
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  url:
    hostname: flyt.vigoiks.no
    basePath: path
  ingress:
    enabled: true
    basePath: path
    middlewares:
      - fint-flyt-auth-forward-sso
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx3G -Xms2G'
    - name: fint.flyt.gateway.application.archive.client.fint-archive.authorization.enable
      value: 'true'
    - name: fint.flyt.resource-server.security.api.internal.enabled
      value: "true"
    - name: fint.flyt.gateway.application.archive.client.fint-archive.base-url
      value: path
    - name: fint.flyt.resource-server.security.api.internal.authorized-org-id-role-pairs-json
      value: |
        {
          "fintlabs.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
        }
  onePassword:
    itemPath: path
  envFrom:
    - secretRef:
        name: fint-flyt-archive-fint-client
    - secretRef:
        name: fint-flyt-file-oauth2-client
  resources:
    limits:
      memory: "3Gi"
      cpu: "500m"
    requests:
      memory: "2Gi"
      cpu: "100m"
  probes:
    readiness:
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  observability:
    metrics:
      enabled: true
      port: "8080"
      path: /actuator/prometheus
  prometheus:
    enabled: true
    port: "8080"
    path: /actuator/prometheus