apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-archive-gateway_bfk_no
      fintlabs.no/org-id: bfk.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-archive-gateway_bfk_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "bfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "bfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/bfk-no"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/beta/bfk-no/actuator/prometheus"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/bfk-no/api/intern/arkiv"
      - op: replace
        path: "/spec/env/3/value"
        value: "https://beta.felleskomponent.no"
      - op: replace
        path: "/spec/env/4/value"
        value: |
          {
            "bfk.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "frid-iks.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-v1-slack-webhook"
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/bfk-no/actuator/health"
    target:
      kind: Application
      name: fint-flyt-archive-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-archive-fint-client_bfk_no"
      - op: replace
        path: "/spec/orgId"
        value: "bfk.no"
    target:
      kind: FintClient
      name: fint-flyt-archive-fint-client

